### **Dataset Columns:**

* **YEAR**: The year in which the data was recorded (ranging from 2018–2022).

  * Corresponds to the ACS survey year.


* **WEIGHT**: Person-level survey weight (PERWT in IPUMS ACS).

  * Used to scale each individual record so the sample represents the U.S. population accurately.
  * All descriptive statistics should apply this weight to maintain representativeness.


* **TOTAL_INCOME**: Total personal income (INCTOT).

  * Includes wage income, business income, investment income, retirement income, and other income sources.
  * Reported in U.S. dollars (USD).


* **WAGE_INCOME**: Wage and salary income (INCWAGE).

  * Income received from employers before deductions.
  * Reported in U.S. dollars (USD).


* **TOTAL_EARNINGS**: Total earned income (INCEARN).

  * Includes wage/salary income and self-employment income.
  * Reported in U.S. dollars (USD).


* **STATE**: State of residence (STATEFIP).

  * Identifies the U.S. state where the respondent resides.
  * Based on Federal Information Processing Standards (FIPS) codes.


* **REGION**: Study region classification (constructed variable).

  * California
  * Rest of United States
    * Study Design Note:
        In Canada, Ontario was selected as the focal province.
        In the United States, California was chosen because it is comparable to Ontario in terms of population size, economic scale, immigrant concentration and labor market diversity.

This allows for more meaningful subnational comparison rather than full-country aggregation.



* **GENDER**: Biological sex of the respondent (SEX).

  * 1 = Male
  * 2 = Female


* **IMMIGRANT_STATUS**: Immigrant classification derived from birthplace (BPL).

  * Born in US = Born in the United States.
  * Immigrant = Born outside the United States.
  * Constructed variable to harmonize with Canadian immigrant status definition.


* **EDUCATION**: Educational attainment level.

  * Less than high school
  * Graduated high school or partial postsecondary
  * Non-university postsecondary certificate/diploma
  * University degree or certificate

Importing the necessary Libraries.

In [ ]:
import pandas as pd
import numpy as np

Reading in the file.

In [ ]:
df = pd.read_csv("./us_df.csv")
df.head()

,YEAR,STATEFIP,PERWT,SEX,AGE,MARST,BPL,BPLD,EDUC,EDUCD,INCTOT,INCWAGE,INCEARN
0,2018,6,107,2,60,1,200,20000,1,15,0,0,0
1,2018,17,234,1,2,6,17,1700,0,1,9999999,999999,0
2,2018,12,240,1,20,6,12,1200,6,61,20000,20000,20000
3,2018,10,229,2,0,6,12,1200,0,1,9999999,999999,0
4,2018,6,94,1,56,6,6,600,10,101,0,0,0

Changing the columns to more readable names.

In [ ]:
df = df.rename(columns={
    "YEAR": "year",
    "STATEFIP": "state_code",
    "PERWT": "weight",
    "SEX": "gender_code",
    "AGE": "age",
    "MARST": "marital_status_code",
    "EDUC": "education_code",
    "EDUCD": "education_detail",
    "BPL": "birthplace_code",
    "BPLD": "birthplace_detail",
    "INCTOT": "total_income",
    "INCWAGE": "wage_income",
    "INCEARN": "total_earnings"
})

Confirming that the Column names are readable.

In [ ]:
df.head()

,year,state_code,weight,gender_code,age,marital_status_code,birthplace_code,birthplace_detail,education_code,education_detail,total_income,wage_income,total_earnings
0,2018,6,107,2,60,1,200,20000,1,15,0,0,0
1,2018,17,234,1,2,6,17,1700,0,1,9999999,999999,0
2,2018,12,240,1,20,6,12,1200,6,61,20000,20000,20000
3,2018,10,229,2,0,6,12,1200,0,1,9999999,999999,0
4,2018,6,94,1,56,6,6,600,10,101,0,0,0

Checking for detailed information about the data.

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 524290 entries, 0 to 524289
Data columns (total 13 columns):
 #   Column               Non-Null Count   Dtype
---  ------               --------------   -----
 0   year                 524290 non-null  int64
 1   state_code           524290 non-null  int64
 2   weight               524290 non-null  int64
 3   gender_code          524290 non-null  int64
 4   age                  524290 non-null  int64
 5   marital_status_code  524290 non-null  int64
 6   birthplace_code      524290 non-null  int64
 7   birthplace_detail    524290 non-null  int64
 8   education_code       524290 non-null  int64
 9   education_detail     524290 non-null  int64
 10  total_income         524290 non-null  int64
 11  wage_income          524290 non-null  int64
 12  total_earnings       524290 non-null  int64
dtypes: int64(13)
memory usage: 52.0 MB

Checking for Missing Values.

In [ ]:
df_missing = df.isnull().sum()
df_missing

year                   0
state_code             0
weight                 0
gender_code            0
age                    0
marital_status_code    0
birthplace_code        0
birthplace_detail      0
education_code         0
education_detail       0
total_income           0
wage_income            0
total_earnings         0
dtype: int64

Mapping the correct values for each state in the State code column.

In [ ]:
state_codes = {
    1: "Alabama",
    2: "Alaska",
    4: "Arizona",
    5: "Arkansas",
    6: "California",
    8: "Colorado",
    9: "Connecticut",
    10: "Delaware",
    11: "District of Columbia",
    12: "Florida",
    13: "Georgia",
    15: "Hawaii",
    16: "Idaho",
    17: "Illinois",
    18: "Indiana",
    19: "Iowa",
    20: "Kansas",
    21: "Kentucky",
    22: "Louisiana",
    23: "Maine",
    24: "Maryland",
    25: "Massachusetts",
    26: "Michigan",
    27: "Minnesota",
    28: "Mississippi",
    29: "Missouri",
    30: "Montana",
    31: "Nebraska",
    32: "Nevada",
    33: "New Hampshire",
    34: "New Jersey",
    35: "New Mexico",
    36: "New York",
    37: "North Carolina",
    38: "North Dakota",
    39: "Ohio",
    40: "Oklahoma",
    41: "Oregon",
    42: "Pennsylvania",
    44: "Rhode Island",
    45: "South Carolina",
    46: "South Dakota",
    47: "Tennessee",
    48: "Texas",
    49: "Utah",
    50: "Vermont",
    51: "Virginia",
    53: "Washington",
    54: "West Virginia",
    55: "Wisconsin",
    56: "Wyoming"
}

df["state"] = df["state_code"].map(state_codes)

In [ ]:
df = df.dropna(subset=['state'])

Creating a region column

In [ ]:
df['region'] = np.where(df['state'] =="California", "California", "Rest of US")
df['region'].value_counts()

region
Rest of US    339404
California    184886
Name: count, dtype: int64

Mapping the values for the Gender columns.

In [ ]:
gender_map = {
    1: "Male",
    2: "Female",
    9: 'Unknown'
}

df["gender"] = df["gender_code"].map(gender_map)

In [ ]:
df = df.dropna(subset=['gender'])

Creating the imigrant status column from the Birthplace code column.

In [ ]:
df['immigrant_status'] = df['birthplace_code'].apply(
    lambda x: "Born in US" if x in state_codes else "Immigrant"
)

In [ ]:
df['immigrant_status'].value_counts()

immigrant_status
Born in US    420005
Immigrant     104285
Name: count, dtype: int64

Creating the Education column from the Education_detail column.

In [ ]:
def map_us_education(code):
    if pd.isna(code) or code in [0, 99, 999]:
        return np.nan
    elif code <= 61:
        return "Less than high school"
    elif 62 <= code <= 64:
        return "High school diploma"
    elif 65 <= code <= 90:
        return "Postsecondary certificate or diploma"
    elif code >= 100:
        return "University degree"
    else:
        return np.nan

In [ ]:
df["education"] = df["education_detail"].apply(map_us_education)

In the total income column, we are keeping the negative values as a result of information from the documentation as this shows us that there was real losses and it's very much valid.

Also, we noticed high values like 999999 and from the documentation, we've also noticed that it's not a real income so we have to drop it.

In [ ]:
df['total_income'] = df['total_income'].replace([9999999, 9999998], pd.NA)

In [ ]:
df['wage_income'] = df['wage_income'].replace([999999, 999998], pd.NA)

In [ ]:
df['total_income'] = pd.to_numeric(df['total_income'], errors='coerce')
df['wage_income'] = pd.to_numeric(df['wage_income'], errors='coerce')
df['total_earnings'] = pd.to_numeric(df['total_earnings'], errors='coerce')

In [ ]:
df.columns

Index(['year', 'state_code', 'weight', 'gender_code', 'age',
       'marital_status_code', 'birthplace_code', 'birthplace_detail',
       'education_code', 'education_detail', 'total_income', 'wage_income',
       'total_earnings', 'state', 'region', 'gender', 'immigrant_status',
       'education'],
      dtype='object')

Dropping the columns that we don't need.

In [ ]:
cols_to_drop = ['gender_code', 'state_code', 'age', 'marital_status_code', 'education_code', 'education_detail', 'birthplace_code', 'birthplace_detail']

df = df.drop(columns=cols_to_drop)

Dropping missing columns in the Education detail and Missing Income.

In [ ]:
df = df.dropna(subset=['education', 'total_income'])

Checking the final outcome of the first 5 rows after cleaning the US data.

In [ ]:
df.head()

,year,weight,total_income,wage_income,total_earnings,state,region,gender,immigrant_status,education
0,2018,107,0.0,0.0,0,California,California,Female,Immigrant,Less than high school
2,2018,240,20000.0,20000.0,20000,Florida,Rest of US,Male,Born in US,Less than high school
4,2018,94,0.0,0.0,0,California,California,Male,Born in US,University degree
6,2018,175,103700.0,0.0,0,Arizona,Rest of US,Male,Born in US,High school diploma
7,2018,49,40000.0,40000.0,40000,Georgia,Rest of US,Female,Born in US,University degree

Checking the descriptive statistics of the data.

In [ ]:
df.describe()

,year,weight,total_income,wage_income,total_earnings
count,430962.000000,430962.000000,4.309620e+05,424253.000000,4.309620e+05
mean,2020.004806,171.619338,4.543510e+04,33632.090587,3.547384e+04
std,1.415071,154.809427,7.046422e+04,61223.923501,6.442130e+04
min,2018.000000,1.000000,-9.100000e+03,0.000000,-9.300000e+03
25%,2019.000000,77.000000,8.300000e+03,0.000000,0.000000e+00
50%,2020.000000,122.000000,2.620000e+04,12000.000000,1.500000e+04
75%,2021.000000,212.000000,5.630000e+04,45000.000000,4.800000e+04
max,2022.000000,3987.000000,1.442800e+06,791000.000000,1.186000e+06

Checking for the number of unique values in the dataset.

In [ ]:
df.nunique()

year                    5
weight               1675
total_income        10357
wage_income           985
total_earnings       2223
state                  19
region                  2
gender                  2
immigrant_status        2
education               4
dtype: int64

### **Downloading the new compiled dataset.**

In [ ]:
#downloading the data

# df.to_csv('us_df_clean.csv', index=False)