## Statistics Canada, Canadian Income Survey (CIS) Public Use Microdata File (PUMF), 2018–2022 editions.

### Dataset Columns:

* **YEAR**: The year in which the data was recorded (ranging from 2018-2022).


* **PUMFID**: Public Use Microdata File (PUMF) household identifier.

  * A unique numeric ID assigned to each household.

* **PERSONID**: Unique individual identifier within the dataset.

  * Each person in a household receives a distinct ID.

* **PROV**: Province or territory of residence.

  * `10 = Newfoundland and Labrador`
  * `11 = Prince Edward Island`
  * `12 = Nova Scotia`
  * `13 = New Brunswick`
  * `24 = Quebec`
  * `35 = Ontario`
  * `46 = Manitoba`
  * `47 = Saskatchewan`
  * `48 = Alberta`
  * `59 = British Columbia`
  * `60 = Yukon`
  * `61 = Northwest Territories`
  * `62 = Nunavut`

* **FWEIGHT**: Final survey weight.

  * Used to scale each record so the sample represents the Canadian population accurately.

* **AGEGP**: Coded `4–15`, typically representing grouped age ranges.

  * `04 = 15-17`
  * `05 = 18-24`
  * `06 = 25-29`
  * `07 = 30-34`
  * `08 = 35-39`
  * `09 = 40-44`
  * `10 = 45-49`
  * `11 = 50-54`
  * `12 = 55-59`
  * `13 = 60-64`
  * `14 = 65-69`
  * `15 = 70+`

* **SEX**: Sex of respondent.

  * `1 = Male`
  * `2 = Female`

* **MARSTP**: Marital status (person-level).

  * `1 = Married`
  * `2 = Common-law`
  * `3 = Separated, divorced or widowed`
  * `4 = Single (never married)`

* **HLEV2G**: Highest level of education attained.

  * `1 = Less than high school`
  * `2 = Graduated high school or partial postsecondary`
  * `3 = Non-university postsecondary certificate/diploma`
  * `4 = University degree or certificate`
  * `9 = Not stated`

* **IMMST**: Immigration status.

  * `1 = landed immigrant`
  * `2 = non-immigrant (born in Canada)`
  * `9 = Not stated / missing`

* **VISMINFL**: Visible minority flag, available only in the 2021 and 2022 datasets.

  * `1 = Visible minority`
  * `2 = Not a visible minority`
  * `9 = Not stated / missing`

* **EARNG**: Total employment earnings (including wages, salaries, and self-employment income).

  * Reported in Canadian dollars.

* **WGSAL**: Wages and salaries only.

  * A subset of total earnings.

* **TTINC**: Total personal income from all sources (before taxes).

  * Includes wages, self-employment, government transfers, investment income, etc.

#### Importing all the necessary Libraries needed.

In [ ]:
import pandas as pd
import warnings
warnings.filterwarnings("ignore")

## **1.2.** Data Preprocessing and Cleaning:

**1.2.1.** Read the dataset:

In [ ]:
cis_data = pd.read_csv('./cis_data_raw.csv')
cis_data.head()

,YEAR,PUMFID,PERSONID,PROV,FWEIGHT,AGEGP,SEX,MARSTP,HLEV2G,IMMST,VISMINFL,EARNG,WGSAL,TTINC
0,2018,2129,212901,35,208.9708,6,2,2,3,2,NaN,50000,50000,50125
1,2018,2129,212902,35,208.9708,6,1,2,4,2,NaN,49000,49000,49225
2,2018,2130,213001,59,1101.2217,10,2,2,4,2,NaN,92500,92500,93900
3,2018,2130,213002,59,1101.2217,12,2,2,4,2,NaN,49000,0,49375
4,2018,2131,213101,47,165.3016,12,2,1,2,2,NaN,21000,0,21000

**1.2.2.** Changing the Column names into something readable.

In [ ]:
cis_data.rename(columns={
    "YEAR": "year",
    "PUMFID": "household_id",
    "PERSONID": "person_id",
    "PROV": "geography",
    "FWEIGHT": "weight",
    "AGEGP": "age_group",
    "SEX": "gender",
    "MARSTP": "marital_status",
    "HLEV2G": "education",
    "IMMST": "immigrant_status",
    "VISMINFL": "visible_minority",
    "EARNG": "earnings",
    "WGSAL": "wages_salary",
    "TTINC": "total_income"
}, inplace=True)

**1.2.2.1.** Confirming that the column names are readable.

In [ ]:
cis_data.head()

,year,household_id,person_id,geography,weight,age_group,gender,marital_status,education,immigrant_status,visible_minority,earnings,wages_salary,total_income
0,2018,2129,212901,35,208.9708,6,2,2,3,2,NaN,50000,50000,50125
1,2018,2129,212902,35,208.9708,6,1,2,4,2,NaN,49000,49000,49225
2,2018,2130,213001,59,1101.2217,10,2,2,4,2,NaN,92500,92500,93900
3,2018,2130,213002,59,1101.2217,12,2,2,4,2,NaN,49000,0,49375
4,2018,2131,213101,47,165.3016,12,2,1,2,2,NaN,21000,0,21000

**1.2.3.** Checking for detailed information about the data.

In [ ]:
cis_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 378138 entries, 0 to 378137
Data columns (total 14 columns):
 #   Column            Non-Null Count   Dtype
---  ------            --------------   -----
 0   year              378138 non-null  int64
 1   household_id      378138 non-null  int64
 2   person_id         378138 non-null  int64
 3   geography         378138 non-null  int64
 4   weight            378138 non-null  float64
 5   age_group         378138 non-null  int64
 6   gender            378138 non-null  int64
 7   marital_status    378138 non-null  int64
 8   education         378138 non-null  int64
 9   immigrant_status  378138 non-null  int64
 10  visible_minority  246895 non-null  float64
 11  earnings          378138 non-null  int64
 12  wages_salary      378138 non-null  int64
 13  total_income      378138 non-null  int64
dtypes: float64(2), int64(12)
memory usage: 40.4 MB

**1.2.4.** Checking for missing values.

In [ ]:
cis_data_missing= cis_data.isnull().sum()
cis_data_missing

year                     0
household_id             0
person_id                0
geography                0
weight                   0
age_group                0
gender                   0
marital_status           0
education                0
immigrant_status         0
visible_minority    131243
earnings                 0
wages_salary             0
total_income             0
dtype: int64

**1.2.5.** Creating a region column from Geography column.

**1.2.5.1.** Mapping the correct values for each province in the Geography column.

In [ ]:
province_map = {
    10: "Newfoundland and Labrador",
    11: "Prince Edward Island",
    12: "Nova Scotia",
    13: "New Brunswick",
    24: "Quebec",
    35: "Ontario",
    46: "Manitoba",
    47: "Saskatchewan",
    48: "Alberta",
    59: "British Columbia",
    60: "Yukon",
    61: "Northwest Territories",
    62: "Nunavut"
}

cis_data['geography'] = cis_data['geography'].map(province_map)

In [ ]:
cis_data = cis_data.dropna(subset=['geography'])

**1.2.5.2.** Creating a region column from geography column.

In [ ]:
cis_data['region'] = cis_data['geography'].apply(
    lambda x: 'Ontario' if x == 'Ontario' else 'Rest of Canada'
)

**1.2.6.** Mapping the numerical values in the 'Education' column to descriptive categories

**1.2.6.1.** Mapping the correct values for each education status.

In [ ]:
education_map = {
    1: "Less than high school",
    2: "High school diploma",
    3: "Postsecondary certificate or diploma",
    4: "University degree",
    9: "Not stated"
}

cis_data['education'] = cis_data['education'].map(education_map)

**1.2.6.2.** Dropping the Missing entries.

In [ ]:
cis_data = cis_data[cis_data['education'] != "Not stated"]

**1.2.7.** Mapping the numerical values in the 'Gender' column to its descriptive category.

In [ ]:
gender_map = {
    1: "Male",
    2: "Female"
}
cis_data['gender'] = cis_data['gender'].map(gender_map)

**1.2.8.** Mapping the numerical values in the 'Immigrant' column to its descriptive category.

**1.2.8.1.** Mapping the correct values for each Immigration status.

In [ ]:
immigrant_map = {
    1: "Immigrant",
    2: "Born in Canada (non-immigrant)",
    9: "Not stated / missing"
}

cis_data['immigrant_status'] = cis_data['immigrant_status'].map(immigrant_map)

**1.2.8.2.** Dropping the Missing entries.

In [ ]:
cis_data = cis_data[cis_data['immigrant_status'] != "Not stated / missing"]

**1.2.9.** Dropping the Age Group column.

In [ ]:
cis_data = cis_data.drop(columns=['age_group'])

**1.2.10.** Dropping the visible_minority column.

This column was removed because it does not directly address our analytical research questions. It also contains a significant number of missing (NaN) values, which could negatively affect the quality and reliability of the analysis if retained.

In [ ]:
cis_data = cis_data.drop(columns=['visible_minority'])

**1.2.11.** Dropping the marital_status, household_id and person_id column.

In [ ]:
cis_data = cis_data.drop(columns=['marital_status', 'household_id', 'person_id'])

**1.2.12.** Removing negative income values.

In [ ]:
cis_data = cis_data[cis_data['total_income'] >= 0]

**1.2.13.** Reseting the index of the dataset

In [ ]:
cis_data.reset_index(drop=True, inplace=True)

**1.2.14.** Checking the final outcome of the first 5 rows after cleaning the "CIS" Data.

In [ ]:
cis_data.head()

,year,geography,weight,gender,education,immigrant_status,earnings,wages_salary,total_income,region
0,2018,Ontario,208.9708,Female,Postsecondary certificate or diploma,Born in Canada (non-immigrant),50000,50000,50125,Ontario
1,2018,Ontario,208.9708,Male,University degree,Born in Canada (non-immigrant),49000,49000,49225,Ontario
2,2018,British Columbia,1101.2217,Female,University degree,Born in Canada (non-immigrant),92500,92500,93900,Rest of Canada
3,2018,British Columbia,1101.2217,Female,University degree,Born in Canada (non-immigrant),49000,0,49375,Rest of Canada
4,2018,Saskatchewan,165.3016,Female,High school diploma,Born in Canada (non-immigrant),21000,0,21000,Rest of Canada

**1.2.15.** Checking descriptive statistics of the data.

In [ ]:
cis_data.describe()

                year         weight      earnings  wages_salary  total_income
count  346897.000000  346897.000000  3.468970e+05  3.468970e+05  3.468970e+05
mean     2020.031344     389.887083  3.613836e+04  3.437311e+04  5.422182e+04
std         1.394208     469.487581  5.224695e+04  5.132629e+04  5.374767e+04
min      2018.000000      10.003100 -1.000000e+05  0.000000e+00  0.000000e+00
25%      2019.000000     125.471100  0.000000e+00  0.000000e+00  2.250000e+04
50%      2020.000000     223.739300  1.700000e+04  1.300000e+04  4.260000e+04
75%      2021.000000     456.926500  5.750000e+04  5.500000e+04  7.062500e+04
max      2022.000000   10079.752800  1.340000e+06  1.300000e+06  1.772450e+06

**1.2.16.** Checking for the number of unique values in the dataset.

In [ ]:
cis_data.nunique()

year                     5
geography               10
weight              170788
gender                   2
education                4
immigrant_status         2
earnings              4547
wages_salary           269
total_income         11099
region                   2
dtype: int64

**1.2.17.** Checking for missing values after cleaning the dataset.

In [ ]:
cis_data.isnull().sum()

year                0
geography           0
weight              0
gender              0
education           0
immigrant_status    0
earnings            0
wages_salary        0
total_income        0
region              0
dtype: int64

**1.2.18.** Checking for detailed information about the dataset after cleaning.

In [ ]:
cis_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 346897 entries, 0 to 346896
Data columns (total 10 columns):
 #   Column            Non-Null Count   Dtype
---  ------            --------------   -----
 0   year              346897 non-null  int64
 1   geography         346897 non-null  object
 2   weight            346897 non-null  float64
 3   gender            346897 non-null  object
 4   education         346897 non-null  object
 5   immigrant_status  346897 non-null  object
 6   earnings          346897 non-null  int64
 7   wages_salary      346897 non-null  int64
 8   total_income      346897 non-null  int64
 9   region            346897 non-null  object
dtypes: float64(1), int64(4), object(5)
memory usage: 26.5+ MB