## Statistics Canada, Canadian Income Survey (CIS) Public Use Microdata File (PUMF), 2018–2022 editions.

### Dataset Columns:

* **YEAR**: The year in which the data was recorded (ranging from 2018-2022).


* **PUMFID**: Public Use Microdata File (PUMF) household identifier.

  * A unique numeric ID assigned to each household.

* **PERSONID**: Unique individual identifier within the dataset.

  * Each person in a household receives a distinct ID.

* **PROV**: Province or territory of residence.

  * `10 = Newfoundland and Labrador`
  * `11 = Prince Edward Island`
  * `12 = Nova Scotia`
  * `13 = New Brunswick`
  * `24 = Quebec`
  * `35 = Ontario`
  * `46 = Manitoba`
  * `47 = Saskatchewan`
  * `48 = Alberta`
  * `59 = British Columbia`
  * `60 = Yukon`
  * `61 = Northwest Territories`
  * `62 = Nunavut`

* **FWEIGHT**: Final survey weight.

  * Used to scale each record so the sample represents the Canadian population accurately.

* **AGEGP**: Coded `4–15`, typically representing grouped age ranges.

  * `04 = 15-17`
  * `05 = 18-24`
  * `06 = 25-29`
  * `07 = 30-34`
  * `08 = 35-39`
  * `09 = 40-44`
  * `10 = 45-49`
  * `11 = 50-54`
  * `12 = 55-59`
  * `13 = 60-64`
  * `14 = 65-69`
  * `15 = 70+`

* **SEX**: Sex of respondent.

  * `1 = Male`
  * `2 = Female`

* **MARSTP**: Marital status (person-level).

  * `1 = Married`
  * `2 = Common-law`
  * `3 = Separated, divorced or widowed`
  * `4 = Single (never married)`

* **HLEV2G**: Highest level of education attained.

  * `1 = Less than high school`
  * `2 = Graduated high school or partial postsecondary`
  * `3 = Non-university postsecondary certificate/diploma`
  * `4 = University degree or certificate`
  * `9 = Not stated`

* **IMMST**: Immigration status.

  * `1 = landed immigrant`
  * `2 = non-immigrant (born in Canada)`
  * `9 = Not stated / missing`

* **VISMINFL**: Visible minority flag, available only in the 2021 and 2022 datasets.

  * `1 = Visible minority`
  * `2 = Not a visible minority`
  * `9 = Not stated / missing`

* **EARNG**: Total employment earnings (including wages, salaries, and self-employment income).

  * Reported in Canadian dollars.

* **WGSAL**: Wages and salaries only.

  * A subset of total earnings.

* **TTINC**: Total personal income from all sources (before taxes).

  * Includes wages, self-employment, government transfers, investment income, etc.

## **1.2.** Data Preprocessing and Cleaning:

**1.2.1.** Read the dataset:

In [ ]:
cis_data = pd.read_csv('./cis_data_raw.csv')
cis_data.head()

,YEAR,PUMFID,PERSONID,PROV,FWEIGHT,AGEGP,SEX,MARSTP,HLEV2G,IMMST,VISMINFL,EARNG,WGSAL,TTINC
0,2018,2129,212901,35,208.9708,6,2,2,3,2,NaN,50000,50000,50125
1,2018,2129,212902,35,208.9708,6,1,2,4,2,NaN,49000,49000,49225
2,2018,2130,213001,59,1101.2217,10,2,2,4,2,NaN,92500,92500,93900
3,2018,2130,213002,59,1101.2217,12,2,2,4,2,NaN,49000,0,49375
4,2018,2131,213101,47,165.3016,12,2,1,2,2,NaN,21000,0,21000

**1.2.2.** Changing the Column names into something readable.

In [ ]:
cis_data.rename(columns={
    "YEAR": "year",
    "PUMFID": "household_id",
    "PERSONID": "person_id",
    "PROV": "geography",
    "FWEIGHT": "weight",
    "AGEGP": "age_group",
    "SEX": "gender",
    "MARSTP": "marital_status",
    "HLEV2G": "education",
    "IMMST": "immigrant_status",
    "VISMINFL": "visible_minority",
    "EARNG": "earnings",
    "WGSAL": "wages_salary",
    "TTINC": "total_income"
}, inplace=True)

**1.2.2.1.** Confirming that the column names are readable.

In [ ]:
cis_data.head()

,year,household_id,person_id,geography,weight,age_group,gender,marital_status,education,immigrant_status,visible_minority,earnings,wages_salary,total_income
0,2018,2129,212901,35,208.9708,6,2,2,3,2,NaN,50000,50000,50125
1,2018,2129,212902,35,208.9708,6,1,2,4,2,NaN,49000,49000,49225
2,2018,2130,213001,59,1101.2217,10,2,2,4,2,NaN,92500,92500,93900
3,2018,2130,213002,59,1101.2217,12,2,2,4,2,NaN,49000,0,49375
4,2018,2131,213101,47,165.3016,12,2,1,2,2,NaN,21000,0,21000

**1.2.3.** Checking for detailed information about the data.

In [ ]:
cis_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 378138 entries, 0 to 378137
Data columns (total 14 columns):
 #   Column            Non-Null Count   Dtype
---  ------            --------------   -----
 0   year              378138 non-null  int64
 1   household_id      378138 non-null  int64
 2   person_id         378138 non-null  int64
 3   geography         378138 non-null  int64
 4   weight            378138 non-null  float64
 5   age_group         378138 non-null  int64
 6   gender            378138 non-null  int64
 7   marital_status    378138 non-null  int64
 8   education         378138 non-null  int64
 9   immigrant_status  378138 non-null  int64
 10  visible_minority  246895 non-null  float64
 11  earnings          378138 non-null  int64
 12  wages_salary      378138 non-null  int64
 13  total_income      378138 non-null  int64
dtypes: float64(2), int64(12)
memory usage: 40.4 MB

**1.2.4.** Checking for missing values.

In [ ]:
cis_data_missing= cis_data.isnull().sum()
cis_data_missing

year                     0
household_id             0
person_id                0
geography                0
weight                   0
age_group                0
gender                   0
marital_status           0
education                0
immigrant_status         0
visible_minority    131243
earnings                 0
wages_salary             0
total_income             0
dtype: int64

**1.2.5.** Filter the geography column for 'Ontario'.

**1.2.5.1.** Mapping the correct values for each province.

In [ ]:
province_map = {
    10: "Newfoundland and Labrador",
    11: "Prince Edward Island",
    12: "Nova Scotia",
    13: "New Brunswick",
    24: "Quebec",
    35: "Ontario",
    46: "Manitoba",
    47: "Saskatchewan",
    48: "Alberta",
    59: "British Columbia",
    60: "Yukon",
    61: "Northwest Territories",
    62: "Nunavut"
}

cis_data['geography'] = cis_data['geography'].map(province_map)

**1.2.5.2.** Filtering for Ontario

In [ ]:
cis_data = cis_data[cis_data['geography'] == 'Ontario']

**1.2.6.** Mapping the numerical values in the 'Education' column to descriptive categories

**1.2.6.1.** Mapping the correct values for each education status.

In [ ]:
education_map = {
    1: "Less than high school",
    2: "High school diploma",
    3: "Postsecondary certificate or diploma",
    4: "University degree",
    9: "Not stated"
}

cis_data['education'] = cis_data['education'].map(education_map)

**1.2.6.2.** Dropping the Missing entries.

In [ ]:
cis_data = cis_data[cis_data['education'] != "Not stated"]

**1.2.7.** Mapping the numerical values in the 'Gender' column to its descriptive category.

In [ ]:
gender_map = {
    1: "Male",
    2: "Female"
}
cis_data['gender'] = cis_data['gender'].map(gender_map)

**1.2.8.** Mapping the numerical values in the 'Immigrant' column to its descriptive category.

**1.2.8.1.** Mapping the correct values for each Immigration status.

In [ ]:
immigrant_map = {
    1: "Landed immigrant",
    2: "Born in Canada (Non-Immigrant)",
    9: "Not stated / missing"
}

cis_data['immigrant_status'] = cis_data['immigrant_status'].map(immigrant_map)

**1.2.8.2.** Dropping the Missing entries.

In [ ]:
cis_data = cis_data[cis_data['immigrant_status'] != "Not stated / missing"]

**1.2.9.** Mapping the numerical values in the 'marital_status' column to its descriptive category.

**1.2.9.1.** Mapping the correct values for each marital status.

In [ ]:
marital_map = {
    1: "Married",
    2: "Common-law",
    3: "Separated, divorced or widowed",
    4: "Single (never married)"
}

cis_data['marital_status'] = cis_data['marital_status'].map(marital_map)

**1.2.10.** Mapping the numerical values in the 'Age' column to its descriptive category.

**1.2.10.1.** Mapping the correct values for each Age group.

In [ ]:
age_mapping = {
    4: '15-17',
    5: '18-24',
    6: '25-29',
    7: '30-34',
    8: '35-39',
    9: '40-44',
    10: '45-49',
    11: '50-54',
    12: '55-59',
    13: '60-64',
    14: '65-69',
    15: '70+'
}

cis_data['age_group'] = cis_data['age_group'].map(age_mapping)

**1.2.11.** Dropping the visible_minority column.

This column was removed because it does not directly address our analytical research questions. It also contains a significant number of missing (NaN) values, which could negatively affect the quality and reliability of the analysis if retained.

In [ ]:
cis_data = cis_data.drop(columns=['visible_minority'])

**1.2.12.** Reseting the index of the dataset

In [ ]:
cis_data.reset_index(drop=True, inplace=True)

**1.2.13.** Checking the final outcome of the first 5 rows after cleaning the "CIS" Data.

In [ ]:
cis_data.head()

,year,household_id,person_id,geography,weight,age_group,gender,marital_status,education,immigrant_status,earnings,wages_salary,total_income
0,2018,2129,212901,Ontario,208.9708,25-29,Female,Common-law,Postsecondary certificate or diploma,Born in Canada (Non-Immigrant),50000,50000,50125
1,2018,2129,212902,Ontario,208.9708,25-29,Male,Common-law,University degree,Born in Canada (Non-Immigrant),49000,49000,49225
2,2018,2137,213701,Ontario,1329.0825,30-34,Male,Married,Postsecondary certificate or diploma,Born in Canada (Non-Immigrant),0,0,4400
3,2018,2137,213702,Ontario,1329.0825,30-34,Female,Married,University degree,Born in Canada (Non-Immigrant),72500,72500,77225
4,2018,2138,213801,Ontario,340.4773,40-44,Male,Married,Postsecondary certificate or diploma,Born in Canada (Non-Immigrant),50000,50000,50500

**1.2.14.** Checking descriptive statistics of the data.

In [ ]:
cis_data.describe()

,year,household_id,person_id,weight,earnings,wages_salary,total_income
count,105823.000000,105823.000000,1.058230e+05,105823.000000,1.058230e+05,1.058230e+05,1.058230e+05
mean,2020.115438,23510.225083,2.351024e+06,520.311800,3.799525e+04,3.617842e+04,5.680186e+04
std,1.402922,13021.515079,1.302152e+06,553.510354,5.886773e+04,5.782742e+04,6.192554e+04
min,2018.000000,2129.000000,2.129010e+05,11.812600,-1.050000e+05,0.000000e+00,-9.762500e+04
25%,2019.000000,12549.000000,1.254904e+06,188.900000,0.000000e+00,0.000000e+00,2.215000e+04
50%,2020.000000,22932.000000,2.293202e+06,335.410100,1.650000e+04,1.200000e+04,4.380000e+04
75%,2021.000000,33316.000000,3.331601e+06,633.568650,6.000000e+04,5.750000e+04,7.415000e+04
max,2022.000000,56009.000000,5.600902e+06,8863.955800,1.340000e+06,1.300000e+06,1.772450e+06

**1.2.15.** Checking for the number of unique values in the dataset.

In [ ]:
cis_data.nunique()

year                    5
household_id        34744
person_id           75883
geography               1
weight              49797
age_group              12
gender                  2
marital_status          4
education               4
immigrant_status        2
earnings             2591
wages_salary          265
total_income         8793
dtype: int64

**1.2.16.** Checking for missing values after cleaning the dataset.

In [ ]:
cis_data.isnull().sum()

year                0
household_id        0
person_id           0
geography           0
weight              0
age_group           0
gender              0
marital_status      0
education           0
immigrant_status    0
earnings            0
wages_salary        0
total_income        0
dtype: int64

**1.2.17.** Checking for detailed information about the dataset after cleaning.

In [ ]:
cis_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 105823 entries, 0 to 105822
Data columns (total 13 columns):
 #   Column            Non-Null Count   Dtype
---  ------            --------------   -----
 0   year              105823 non-null  int64
 1   household_id      105823 non-null  int64
 2   person_id         105823 non-null  int64
 3   geography         105823 non-null  object
 4   weight            105823 non-null  float64
 5   age_group         105823 non-null  object
 6   gender            105823 non-null  object
 7   marital_status    105823 non-null  object
 8   education         105823 non-null  object
 9   immigrant_status  105823 non-null  object
 10  earnings          105823 non-null  int64
 11  wages_salary      105823 non-null  int64
 12  total_income      105823 non-null  int64
dtypes: float64(1), int64(6), object(6)
memory usage: 10.5+ MB